### PR TITLE
bcm283x:Add support for internal pull resistor used in BCM2711

### LINKED ISSUE #432: Unable to set GPIO pin pull on Raspberry Pi 4
**Describe the bug**
I am trying to configure a GPIO pin on the raspberry pi 4, more specifically the Pin number 29 (Connected to GPIO 5), and set it to pull down however when reading the pin it reports pull up.

This works fine on a raspberry pi 3

**To Reproduce**
1. Run program
```go
package main

import (
	"fmt"
	"log"
	"time"

	"periph.io/x/periph/conn/gpio"
	"periph.io/x/periph/host"
	"periph.io/x/periph/host/rpi"
)

var (
	readPin = rpi.P1_29
)

func main() {
	fmt.Println("Initializing periph host...")
	if _, err := host.Init(); err != nil {
		log.Panicf("failed to initialize periph host: %v", err)
	}

	if err := readPin.In(gpio.PullDown, gpio.NoEdge); err != nil {
		log.Panicf("failed to set read pin to In(): %v", err)
	}

	ticker := time.NewTicker(2 * time.Second)
	want := gpio.Low

	for {
		select {
		case <-ticker.C:
			time.Sleep(time.Millisecond)
			actual := readPin.Read()
			if actual != want {
				log.Printf("ERROR: Actual: %t != Wanted: %t", actual, want)
				continue
			}
			log.Println("EVERYTHING WAS FINE")
		}
	}
}
```
2. Run it.
3. See error
`Actual: true != Wanted: false`

**Expected behavior**
It should set the Pin 29 to Pull Down (Meaning I get `gpio.Low` when reading it) thus printing only `EVERYTHING WAS FINE`

**Platform (please complete the following information):**
 - OS: balenaOS 2.44.0+rev3 (64-bit BETA)
 - Raspberry Pi 4

**Additional context**
Compilation command: `GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build main.go`
Periph version: `v3.6.2`
Go version: `1.13`

The code has been tested on several raspberry pi 3 without any issues

### PR DESCRIPTION
**Pull request by berryboy2012**
Fixes  #432

### CODE REVIEW

**Comment by berryboy2012** [comment]
@googlebot I signed it!

**Comment by berryboy2012** [comment]
Thanks for your reply! As I dig deeper into it, seems that we should rewrite model identification altogether as suggested on raspberry pi's website. https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by berryboy2012** [comment]
Hi, I have updated the code according to your suggestions, could you please look into it? Thanks in advance!
> 
> 
> It'd be good to run
> 
> ```
> periph-smoketest bcm283x
> ```
```
pi@raspberrypi:~/periph/bin $ sudo ./periph-smoketest-arm bcm283x
    0.004ms GPIO6.In(PullDown, NoEdge)
    0.118ms GPIO13.In(PullDown, NoEdge)
    0.213ms GPIO13.In(PullUp, NoEdge)
- Testing DMA PWM
    0.284ms GPIO13.In(PullDown, BothEdges)
    0.667ms GPIO6.PWM(0%, 5kHz)
    0.761ms GPIO6.PWM(100%, 5kHz)
    0.814ms GPIO6.PWM(25%, 5kHz)
    1.525ms GPIO6.PWM(50%, 5kHz)
- Testing PWM
    2.223ms GPIO6.In(PullDown, BothEdges)
    2.520ms GPIO13.PWM(0%, 5kHz)
    2.623ms GPIO13.PWM(100%, 5kHz)
    2.680ms GPIO13.PWM(25%, 5kHz)
    2.960ms GPIO13.PWM(50%, 5kHz)
    3.162ms GPIO13.Out(Low)
- Testing StreamIn
    3.306ms GPIO6.PWM(50%, 5kHz)
    3.773ms GPIO13.StreamIn(PullDown, &{ 10kHz %!s(bool=true)})
fraction 50
```
> ```
> periph-smoketest bcm283x-benchmark -p GPIO4
> ```
```
pi@raspberrypi:~/periph/bin $ sudo ./periph-smoketest-arm bcm283x-benchmark -p GPIO4
ReadNaive               10000000               120 ns/op        8.304MHz
ReadDiscard             10000000               125 ns/op        7.945MHz
ReadSliceLevel          10000000               127 ns/op        7.872MHz
ReadBitsLSBLoop         10000000               130 ns/op        7.682MHz
ReadBitsMSBLoop         10000000               130 ns/op        7.669MHz
ReadBitsLSBUnroll       10000000               125 ns/op        7.983MHz
ReadBitsMSBUnroll       10000000               125 ns/op        7.950MHz
OutClock                 5000000               269 ns/op        3.706MHz
OutSliceLevel            5000000               270 ns/op        3.703MHz
OutBitsLSBLoop           5000000               273 ns/op        3.657MHz
OutBitsMSBLoop           5000000               272 ns/op        3.663MHz
OutBitsLSBUnroll         5000000               269 ns/op        3.714MHz
OutBitsMSBUnrool         5000000               269 ns/op        3.711MHz
FastReadNaive           100000000               19.1 ns/op      52.227MHz
FastReadDiscard         100000000               21.7 ns/op      46.090MHz
FastReadSliceLevel      20000000               119 ns/op        8.367MHz
FastReadBitsLSBLoop     20000000               115 ns/op        8.682MHz
FastReadBitsMSBLoop     20000000               115 ns/op        8.668MHz
FastReadBitsLSBUnrol    20000000               103 ns/op        9.659MHz
FastReadBitsMSBUnrol    20000000               116 ns/op        8.603MHz
FastOutClock            100000000               10.0 ns/op      99.868MHz
FastOutSliceLevel       100000000               11.0 ns/op      91.076MHz
FastOutBitsLSBLoop      100000000               10.0 ns/op      99.639MHz
FastOutBitsMSBLoop      100000000               10.0 ns/op      99.629MHz
FastOutBitsLSBUnroll    100000000               10.2 ns/op      98.470MHz
FastOutBitsMSBUnroll    100000000               10.1 ns/op      99.481MHz
FastOutInterface        100000000               17.8 ns/op      56.143MHz
FastOutMemberVariabl    100000000               10.2 ns/op      98.269MHz
```
> ```
> periph-smoketest sysfs-benchmark
> ```
```
pi@raspberrypi:~/periph/bin $ ./periph-smoketest-arm sysfs-benchmark -p 15
ReadNaive                 300000              4380 ns/op        228.305kHz
ReadDiscard               300000              4551 ns/op        219.702kHz
ReadSliceLevel            300000              4501 ns/op        222.154kHz
ReadBitsLSBLoop           300000              4570 ns/op        218.786kHz
ReadBitsMSBLoop           300000              4499 ns/op        222.264kHz
ReadBitsLSBUnroll         300000              4403 ns/op        227.087kHz
ReadBitsMSBUnroll         300000              4449 ns/op        224.735kHz
OutClock                  300000              4685 ns/op        213.432kHz
OutSliceLevel             300000              4678 ns/op        213.751kHz
OutBitsLSBLoop            300000              4699 ns/op        212.802kHz
OutBitsMSBLoop            300000              4630 ns/op        215.951kHz
OutBitsLSBUnroll          300000              4659 ns/op        214.604kHz
OutBitsMSBUnrool          300000              4738 ns/op        211.042kHz
```

File: host/bcm283x/gpio.go [hunk 1]
```diff
@@ -75,6 +75,10 @@ var (
 	GPIO46 *Pin //
 	// Pins 47~53 are not exposed because using them would lead to immediate SD
 	// Card corruption.
+
+	// Whether uses the old pull resistor setup method before bcm2711.
+	// If true, older method is used, and Pull() won't give useful information.
+	UseLegacyPull = true
```
Comment (maruel) [inline host/bcm283x/gpio.go:81]: I'd prefer this to not be exported, since it's not meant to be used by the user. So I recomment to make it a member of driverGPIO.

File: host/bcm283x/gpio.go [hunk 2]
```diff
@@ -1216,14 +1277,24 @@ func (d *driverGPIO) Init() (bool, error) {
...
 		d.baseAddr = 0x20000000
 		d.dramBus = 0x40000000
-	} else {
+		UseLegacyPull = true
+	} else if strings.Contains(dTCompatible, "bcm2709") {
 		// RPi2+
 		d.baseAddr = 0x3F000000
 		d.dramBus = 0xC0000000
+		UseLegacyPull = true
+	} else {
```
Comment (maruel) [inline host/bcm283x/gpio.go:1291]: Raspberry Pi 3 shows up as bcm2837.
I'll have to boot up my RPi1 and RPiZ to confirm.

File: host/bcm283x/gpio.go [hunk 3]
```diff
@@ -89,6 +89,18 @@ func Present() bool {
 	return false
 }
 
+// Is2711 returns true if running on a Broadcom bcm2711 CPU.
```
[the remark this answers is not in the document]
Comment (maruel) [reply host/bcm283x/gpio.go]: Ok wrote a separate comment to confirm this.

**Comment by maruel** [comment]
gohci

File: host/bcm283x/gpio.go (hunk 2 above)
Comment (berryboy2012) [reply host/bcm283x/gpio.go:1291]: I assume it would be ok if nothing changed after #25 ?

Comment (maruel) [reply host/bcm283x/gpio.go:1291]: Humm it's weird, because in the issue Torsten noted that bcm2709 is returned on a RPi3 Raspbian Jessie but it's definitely bcm2837 when run locally on Raspbian Buster.

I'd prefer to keep add the new check for RPi4 first, then fallback on the previous check. This feels safer, unless you have another idea.

**Comment by maruel** [comment]
The odroid failure looks spurious but I suspect the raspberrypi one is real.

**Comment by berryboy2012** [comment]
> 
> 
> The odroid failure looks spurious but I suspect the raspberrypi one is real.

I think it may be caused by the bcm283x/bcm27xx mess mentioned earlier. My workaround in the last commit is to detect both naming scheme. By the way, while I was searching for this weird problem, I found an official documentation encouraging use of `bcm_host.h` when it comes to determining peripheral addresses. https://www.raspberrypi.org/documentation/hardware/raspberrypi/peripheral_addresses.md

File: host/bcm283x/gpio.go (hunk 2 above)
Comment (berryboy2012) [reply host/bcm283x/gpio.go:1301]: If all we need to worry about are Raspberry Pis (Seems legit as some sources state that those chips are made specifically for RPi.), we can parse revision code found in `/proc/cpuinfo`. Otherwise, I think we can workaround this by detecting both naming schemes.

**Comment by maruel** [comment]
I looked at firmware.git and the implementation is in opt/vc/lib/libbcm_host.so so that's really not helpful on their part.

File: host/bcm283x/gpio.go (hunk 2 above)
Comment (maruel) [reply host/bcm283x/gpio.go:1301]: I think your implementation is fine.

**Comment by maruel** [comment]
gohci

File: host/bcm283x/gpio.go [hunk 4]
```diff
@@ -1191,6 +1251,10 @@ type driverGPIO struct {
 	gpioMemory *gpioMap
 	// gpioBaseAddr is needed for DMA transfers.
 	gpioBaseAddr uint32
+	// Whether uses the old pull resistor setup method before bcm2711.
```
Comment (maruel) [inline host/bcm283x/gpio.go:1254]: FTR documentation should start with the symbol being described, I can do it in a follow up.

File: host/bcm283x/gpio.go [hunk 5]
```diff
@@ -478,10 +506,28 @@ func (p *Pin) WaitForEdge(timeout time.Duration) bool {
...
 func (p *Pin) Pull() gpio.Pull {
-	// TODO(maruel): The best that could be added is to cache the last set value
-	// and return it.
+	// sysfs does not have the capability to read pull resistor.
+	if drvGPIO.gpioMemory != nil {
+		if drvGPIO.useLegacyPull {
+			// TODO(maruel): The best that could be added is to cache the last set value
+			// and return it.
+			return gpio.PullNoChange
+		} else {
```
Comment (maruel) [inline host/bcm283x/gpio.go:518]: This would trigger golint, as in general else after a return is not idiomatic. I can fix in a follow up.

File: host/bcm283x/gpio_test.go [hunk 6]
```diff
@@ -130,6 +130,13 @@ func TestPin(t *testing.T) {
 	if d := p.Read(); d != gpio.Low {
 		t.Fatal(d)
 	}
+	// gpio.PinIn.Pull()
+	if d := p.Pull(); d != gpio.Float {
```
Comment (maruel) [inline host/bcm283x/gpio_test.go:134]: Did you mean PullNoChange?

**Comment by maruel** [comment]
I forgot to note, you can add yourself to AUTHORS and CONTRIBUTORS if you want.

File: host/bcm283x/gpio_test.go (hunk 6 above)
Comment (berryboy2012) [reply host/bcm283x/gpio_test.go:134]: Nope, in bcm2711, we can (finally) read the state of pull resistors. Since the pin was previously set to Float, it should give us the correct result on a bcm2711.

Comment (maruel) [reply host/bcm283x/gpio_test.go:134]: Ah because this code runs in RPi4 mode, right. Thanks!

File: host/bcm283x/gpio.go (hunk 5 above)
Comment (maruel) [reply host/bcm283x/gpio.go:518]: Fixed in a follow up.

File: host/bcm283x/gpio.go (hunk 4 above)
Comment (maruel) [reply host/bcm283x/gpio.go:1254]: Fixed in a follow up.
