### PR TITLE
bcm283x: Fixes #226: unrolling DMA controlBlocks

### LINKED ISSUE #226: bcm283x: gpio.PWM() Interfering with gpio.Out()
At it simplest a call to
``bcm283x.GPIO25.PWM(dutyCycle, period) //rpi.P1_22``
causes a subsequent call to
``bcm283x.GPIO27.Out(gpio.High) //rpi.P1_13``
to not do-the-right-thing.
**Observed behaviour:** physical pin 13 outputs a random square wave
**Expected behaviour:** physical pin 13 should output a high signal

	package main

	import (
		"bufio"
		"fmt"
		"os"
		"time"

		"periph.io/x/periph/conn/gpio"
		"periph.io/x/periph/host"
		"periph.io/x/periph/host/bcm283x"
	)

	func main() {
		reader := bufio.NewReader(os.Stdin)
		host.Init()

		fmt.Println("one")
		fmt.Println(" - both pin 22 and 13 low or the state they were in at the end of the previous run")
		reader.ReadRune()

		dutyCycle := gpio.Duty(gpio.DutyHalf)
		period := time.Millisecond * 20.0
		bcm283x.GPIO25.PWM(dutyCycle, period) //rpi.P1_22

		fmt.Println("two")
		fmt.Println(" - pin 22 50% dutyCycle 20ms period")
		fmt.Println(" - pin 13 low first run after reboot, random square wave if not first run")
		reader.ReadRune()

		bcm283x.GPIO27.Out(gpio.High) //rpi.P1_13

		fmt.Println("three")
		fmt.Println(" - pin 22 50% dutyCycle 20ms period")
		fmt.Println(" - pin 13 random square wave")
		reader.ReadRune()

		bcm283x.GPIO25.Halt()

		fmt.Println("four")
		fmt.Println(" - both pin 22 and 13 low or high")
	}

I've observed this happening to more than just pin13 though only after setting an output. I've not done an exhaustive search. This random square wave behaviour seems to persist multiple runs and clears on reboot.

### PR DESCRIPTION
**Pull request by bezineb5**
The DMA controlBlocks are unrolled and the parameter txLen is set to a fixed value.

### CODE REVIEW

File: host/bcm283x/dma.go [hunk 1]
```diff
@@ -743,13 +743,15 @@ func startPWMbyDMA(p *Pin, rng, data uint32) (*dmaChannel, *videocore.Mem, error
 	if drvDMA.dmaMemory == nil {
 		return nil, nil, errors.New("bcm283x-dma is not initialized; try running as root?")
 	}
-	cb, buf, err := allocateCB(2*32 + 4) // 2 CBs + mask
+
+	// Hardcoded len(controlBlock) == 32
+	cbBytes := uint32(32)
```
Comment (maruel) [inline host/bcm283x/dma.go:748]: can you make it a const? No idea why I hadn't done it before.

File: host/bcm283x/dma.go [hunk 2]
```diff
@@ -758,20 +760,30 @@ func startPWMbyDMA(p *Pin, rng, data uint32) (*dmaChannel, *videocore.Mem, error
 		drvGPIO.gpioBaseAddr + 0x1C + 4*uint32(p.number/32), // set
 	}
 	// High
-	if err := cb[0].initBlock(physBit, dest[1], data*4, false, true, false, false, dmaPWM); err != nil {
-		_ = buf.Close()
-		return nil, nil, err
+	ptr := physBuf
+	for i := uint32(0); i < data; i++ {
```
Comment (maruel) [inline host/bcm283x/dma.go:764]: My only worry is that this could be fairly large in egregious cases. Can you calculate what's the worst case?

For example if PWM(DutyHalf, 1Hz) is called, rng would be huge.

Comment (bezineb5) [reply host/bcm283x/dma.go:764]: With:
drvDMA.pwmDMAFreq = 200 * physic.KiloHertz
freq = 1 * physic.Hertz

We have:
rng := uint64(drvDMA.pwmDMAFreq / freq)
rng = 200 000

And we allocate:
rng*controlBlockSize + 4
200000 * 32 + 4 = 6400004
Rounded to 4KB:
6402048 bytes => 6252 kiB or around 6MiB

So, to progress on that question:
* Is it too much or not (I have frankly no idea)? Maybe I can return an error if it's too much.
* Do you know what kind of device would require such low-frequency PWM signal? I know servos are in the range 50Hz - 200Hz, more than 100kHz for neopixel LEDs, but there's probably plenty of other devices I don't know.
* I like the cleanness of the solution of using only 2 control blocks, but I don't explain why it's unstable with multiple DMA channels. I unfortunately couldn't find much documentation on this. However, shouldn't the source buffer as large as this size?

File: host/bcm283x/dma.go (hunk 1 above)
Comment (bezineb5) [reply host/bcm283x/dma.go]: Done

File: host/bcm283x/dma.go (hunk 2 above)
Comment (maruel) [reply host/bcm283x/dma.go:764]: It's a significant amount, as it's allocated from the GPU memory. The default amount available is 64MiB as per https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md.

1Hz is borderline egregious; 50Hz (like for servos) is 125Kb, which is tolerable. Can you just add a comment about the trade off being made here?

Comment (maruel) [reply host/bcm283x/dma.go:764]: I'd say as documentation for startPWMbyDMA. Technically the CL is good as is, so I can commit and the comment can be added as a follow up, since you already waited a fair amount to get this in.

**Comment by maruel** [comment]
gohci

File: host/bcm283x/dma.go [hunk 3]
```diff
@@ -412,6 +412,8 @@ type controlBlock struct {
 	reserved [2]uint32 // 0x18+0x1C
 }
 
+const controlBlockSize uint32 = 32
```
Comment (maruel) [inline host/bcm283x/dma.go:415]: I'd recommend removing the uint32 type, as then it'll be used as the correct type in context, which will remove the need for casting as you did at line 901.

Thanks for adding one, using 32 everywhere was a bit dumb.

Comment (maruel) [reply host/bcm283x/dma.go:415]: well there's offsetBytes that would be incorrect. So you'd save two casts but add a new one. I'd still vote for removing since it's customary in Go.
